# This file was generated by GoReleaser. DO NOT EDIT.
cask "secrets-gen" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "9dc5e7ad95e8fdca73907db19071d4986a9dc238e876ef1ff827157dabebe6ca"
      url "https://github.com/gray-snyk/secrets-gen/releases/download/v#{version}/secrets-gen_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "88df2a99585b2f555b4a8cf05798d0a7dc89a0bbe1a1b4075c2185d4839c0ef4"
      url "https://github.com/gray-snyk/secrets-gen/releases/download/v#{version}/secrets-gen_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6c57c11e4cc5c9cfb6f12f62ecfa8842521c001a6fa387b42a372b5f43b53c01"
      url "https://github.com/gray-snyk/secrets-gen/releases/download/v#{version}/secrets-gen_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7920101bcddd610df5521577252d01d8c28e78919d3eaad6ceee03408f1be9ce"
      url "https://github.com/gray-snyk/secrets-gen/releases/download/v#{version}/secrets-gen_#{version}_linux_arm64.tar.gz"
    end
  end

  name "secrets-gen"
  desc "Generate fake secrets in real service formats for scanner testing"
  homepage "https://github.com/gray-snyk/secrets-gen"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "secrets-gen"

  # No zap stanza required

end
