# This file was generated by GoReleaser. DO NOT EDIT.
cask "secrets-gen" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "9770c166d0e865523fc84f2d2c97c6f3930e6b51314bc0a535dc753b72a8c221"
      url "https://github.com/gray-snyk/secrets-gen/releases/download/v#{version}/secrets-gen_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "dede8cd326dda1be745f3d8778e7a45abc87196f665e5b5a8b3a9230bcbbfd1b"
      url "https://github.com/gray-snyk/secrets-gen/releases/download/v#{version}/secrets-gen_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b04bd665419e8b18f21a87fe3d138522ce1c3b124e07793adb61d1267b49b6b6"
      url "https://github.com/gray-snyk/secrets-gen/releases/download/v#{version}/secrets-gen_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "eaf7aa5f4005e36cda97052a2a4e012c02b81a124377e22b8272e4fee4cd3526"
      url "https://github.com/gray-snyk/secrets-gen/releases/download/v#{version}/secrets-gen_#{version}_linux_arm64.tar.gz"
    end
  end

  name "secrets-gen"
  desc "Generate fake secrets in real service formats for scanner testing"
  homepage "https://github.com/gray-snyk/secrets-gen"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "secrets-gen"

  # No zap stanza required

end
