# This file was generated by GoReleaser. DO NOT EDIT.
cask "secrets-gen" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "b57a6503b9d99bbe7059f864667deaf4d9a7b318a570da0118f57ea502da2b06"
      url "https://github.com/gray-snyk/secrets-gen/releases/download/v#{version}/secrets-gen_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e5b5cc08cf8c02749d4d058caa9f63b42d6e100ba019cc1b45b1bb34e1987d0c"
      url "https://github.com/gray-snyk/secrets-gen/releases/download/v#{version}/secrets-gen_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8cef1a992cb2e1dc87caff78779ff211cdade8d1f458f32db045dd76da3f3b0f"
      url "https://github.com/gray-snyk/secrets-gen/releases/download/v#{version}/secrets-gen_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "206581b881d44820287b756cc651d8feb3752e4ca8c987744e34b41f3671fe55"
      url "https://github.com/gray-snyk/secrets-gen/releases/download/v#{version}/secrets-gen_#{version}_linux_arm64.tar.gz"
    end
  end

  name "secrets-gen"
  desc "Generate fake secrets in real service formats for scanner testing"
  homepage "https://github.com/gray-snyk/secrets-gen"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "secrets-gen"

  # No zap stanza required

end
